### ISSUE TITLE
GetTimeSeriesAsync returns bad datetimes

### ISSUE THREAD

**Issue by flyingfisch** [pseudomarkets/TwelveDataSharp#1]
All datetime values for GetTimeSeriesAsync are 1/1/0001 12:00:00 AM +00:00

**Comment by flyingfisch** [comment]
I was wrong, looks like this was an implementation error on my part. sorry.

**Comment by ShravanJ** [comment]
~~Thanks for raising this issue. Could you provide some additional details on the Time Series request, such as the symbol and interval used?~~

Edit: Issue was self resolved
