### ISSUE TITLE
GetQuoteAsync does not set Symbol property

### ISSUE THREAD

**Issue by flyingfisch** [pseudomarkets/TwelveDataSharp#2]
Also, if it can't find information for the specified symbol it returns nulls, not sure if this is an issue.

**Comment by ShravanJ** [comment]
Missing symbol in GetQuoteAsync will be addressed in the next release, thanks for the catch. 

Null values are returned as the default response when an invalid symbol is used. To make the response easier to parse for consumers, I can create a new field for the response status to indicate if there was data found or not; this way, you won't have to check each field for being null. I can also make this change in the next release.

**Comment by ShravanJ** [comment]
Updated NuGet: https://www.nuget.org/packages/TwelveDataSharp/1.1.0

Changelog:
* Bug fix for GetQuoteAsync missing symbol
* Added unit tests
* Renamed and improved data model structure
* Added response status for all methods
* Improved null checks on all methods

cc: @flyingfisch
